

POST http://localhost:5000/save-draft HTTP/1.1
content-type: application/json

{     
   "title":"Google neos",
   "content":"this is third lecttue......",
   "tags":"@tanmay,@rushi"
      
}
###
POST http://localhost:5000/publish HTTP/1.1
content-type: application/json

{     
      "id": "68276918cc2d7c45e155db05"
}

###
GET http://localhost:5000/AllBlogs HTTP/1.1
content-type: application/json

###

POST http://localhost:5000/findBlog HTTP/1.1
content-type: application/json

{
     "blog_id":"68276501bbeb86ec17d05a8b"
}